# REQUIREMENTS SPECIFICATION DOCUMENT

# Objective: Development of a Computer manufacturing simulation system.
# Each Development Iteration/Cycle/Sprint Specifys new requirements 
  # to be incrementally added to the computer system.

Sprint_00:
  # Develop code for a computer system with the following features.
    - Should be able to input data from a keyBoard.
    - Should be able to store & retrieve data to & from internal memory.
    - Should be able to process data using the default processing unit.
    - Should be able to output data on a built-in screen.
    - Should be able to connect to WI-FI.
    - Should be able to connect bluetooth device.

Sprint_01:
  # Sprint Goal: Implementing the SOLID Design Principles

  # The Problem:
    # It was discovered that the computer system modeled in the previous iteration was very rigid,
      # In a sense that it does not accomodate variations in;
      # data input devices, Storage devices, Processing devices, and output devices.

    # It was also discovered that the computer system modeled in the previous iteration 
      # forced all computers to support technologies like, WI-Fi, and Bluetooth. 
      # However, due to numerous demands from customers, 
        # the compony now intends to manufacture Computers that do not support Wi-Fi and Bluetooth
        # At relatively lower prices than usual.
    
  # Proposal:
    # You are required to re-model the computer system to be able to fullfil the following requirements
    - Should with ease support variation in Input devices used for inputing data.
    - Should with ease support variation in Storage devices used for 
      storing & retrieving data.
    - Should with ease support variation in Processing devices used for processing data.
    - Should with ease support variation in Output devices used for outputing data.
    - The new model should allow for manufacturing of Computers that do not support the WI-FI technology.
    - The new model should allow for manufacturing of Computers that do not support the bluetooth technology.

Sprint_02:
  # Sprint Goal: Implementing the Singleton Design Pattern
